package com.stage2.CouponProject.models;

import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.List;

/**
 * A class that represents a company object with all it fields
 */
@Entity
@NoArgsConstructor
@Data
@Table (name = "companies")
public class Company {
    /**
     * The company id, autogenerated in the database while being added by the admin
     */
    @Id
    private int id;

    /**
     * The company name
     */
    private String name;

    /**
     * The company email
     */
    private String email;

    /**
     * The company password
     */
    private String password;

    /**
     * An arrayList of type coupon which holds all the company coupons.
     * The relationship between coupons table and company table is One To Many and built by unidirectional strategy.
     */
    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER, orphanRemoval = true)
    @JoinColumn(name = "company_id")
    private List<Coupon> coupons;

    /**
     * This const` receive only the required data.
     * @param name of the company.
     * @param email of the company.
     * @param password of the company.
     * @param coupons of the company.
     */
    public Company(String name, String email, String password, List<Coupon> coupons) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.coupons = coupons;
    }

    /**
     * toString method of the class
     * @return the company details as a string
     */
    @Override
    public String toString() {
        return "Company: " +
                "id - " + id +
                ", name - " + name +
                ", email - " + email +
                ", password - " + password +
                ", coupons - " + coupons;
    }

}
