package com.stage2.CouponProject.models;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.sql.Date;

/**
 * A class that represents a coupon object with all it fields
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table (name ="coupons")
public class Coupon {

    /**
     * The coupon id, autogenerated in the database while being added by the company
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The company id of the company that added this coupon.
     */
    @Column (name = "company_id")
    private int companyId;

    /**
     * The coupon title
     */
    private String title;

    /**
     * The coupon category
     */
    @Enumerated (EnumType.STRING)
    private Category category;

    /**
     * The coupon description - details about the coupon
     */
    private String description;

    /**
     * The start date of the coupon
     */
    private Date startDate;

    /**
     * The end date of the coupon
     */
    private Date endDate;

    /**
     * the coupon amount
     */
    private int amount;

    /**
     * the coupon price
     */
    private double price;

    /**
     * the coupon image as url
     */
    private String image;

    /**
     * This const` receive only the required data.
     * @param title of the coupon
     * @param category  of the coupon
     * @param description  of the coupon
     * @param startDate  of the coupon
     * @param endDate expired date of the coupon
     * @param amount  of available coupon
     * @param price of the coupon
     * @param image url of the coupon
     */
    public Coupon(String title, Category category, String description, Date startDate, Date endDate, int amount, double price, String image) {
        this.title = title;
        this.category = category;
        this.description = description;
        this.startDate = startDate;
        this.endDate = endDate;
        this.amount = amount;
        this.price = price;
        this.image = image;
    }

    /**
     * This const` receive only the required data.
     * @param companyId of the coupon
     * @param title of the coupon
     * @param category  of the coupon
     * @param description  of the coupon
     * @param startDate  of the coupon
     * @param endDate expired date of the coupon
     * @param amount  of available coupon
     * @param price of the coupon
     * @param image url of the coupon
     */
    public Coupon(int companyId, String title, Category category, String description, Date startDate, Date endDate, int amount, double price, String image) {
        this.companyId = companyId;
        this.title = title;
        this.category = category;
        this.description = description;
        this.startDate = startDate;
        this.endDate = endDate;
        this.amount = amount;
        this.price = price;
        this.image = image;
    }

    /**
     * toString method of the class
     *
     * @return the coupon details as a string
     */
    @Override
    public String toString() {
        return "Coupon: " +
                "id - " + id +
                ", companyID - " + companyId +
                ", category - " + category +
                ", title - " + title +
                ", description - " + description +
                ", startDate - " + startDate +
                ", endDate - " + endDate +
                ", amount - " + amount +
                ", price - " + price +
                ", image - " + image;
    }
}
